version: '3'
services:
## -----------------------Servicio data bases -----------------------------
  db_postgres:
    image: "postgres:11.5-alpine"
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: candidate_db, company_db, company_employees_db, project_db, search_tool_db, interviews_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    networks:
      - web_global

## -----------------------Servicio candidate -----------------------------
  app_candidate:
    build: app_candidate/
    environment:
      DATABASE_URL:  postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      db_postgres:
        condition: service_healthy
    volumes:
      - ./app_candidate:/python-docker
    networks:
      - web_global

## -----------------------Servicio company -----------------------------
  app_company:
    build: app_company/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - web_global

## -----------------------Servicio company employees -----------------------------
  app_company_employees:
    build: app_company_employees/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3002:3002"
    expose:
      - "3002"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - web_global

## -----------------------Servicio project -----------------------------
  app_project:
    build: app_project/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3007:3007"
    expose:
      - "3007"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - web_global

## -----------------------Servicio app_search_tool -----------------------------
  app_search_tool:
    build: app_search_tool/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3008:3008"
    expose:
      - "3008"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - web_global

## -----------------------Servicio app_selection_process -----------------------------
  app_selection_process:
    build: app_selection_process/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_postgres:5432/
    ports:
      - "3010:3010"
    expose:
      - "3010"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - web_global

networks:
  web_global:



