###################################
# app_company
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  labels:
    app: company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/abc-jobs-dockers/company:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: "SQLALCHEMY_DATABASE_URI"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: uri
            - name: USERS_URL
              value: http://servicio-app-company/

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-company-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3001
    type: HTTP
    requestPath: /company/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-app-company
  annotations:
    cloud.google.com/backend-config: '{"default": "app-company-config"}'
spec:
  type: NodePort
  selector:
    app: company
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 31021
---
