###################################
# app_candidate
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate
  labels:
    app: candidate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate
  template:
    metadata:
      labels:
        app: candidate
    spec:
      containers:
        - name: candidate
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/abc-jobs-dockers/candidate:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: "SQLALCHEMY_DATABASE_URI"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: uri
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: DATABASE_URL

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-candidate-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3000
    type: HTTP
    requestPath: /candidate/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-app-candidate
  annotations:
    cloud.google.com/backend-config: '{"default": "app-candidates-config"}'
spec:
  type: NodePort
  selector:
    app: candidate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31020
---
