###################################
# app_selection_process
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selection-process
  labels:
    app: selection-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selection-process
  template:
    metadata:
      labels:
        app: selection-process
    spec:
      containers:
        - name: selection-process
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/abc-jobs-dockers/selection-process:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: "SQLALCHEMY_DATABASE_URI"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: uri
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: DATABASE_URL
            - name: PROJECT_URI
              value: http://servicio-app-projects/
            - name: CONTRACT_URI
              value: http://servicio-app-contracts/
            - name: PERFORMANCE_URI
              value: http://servicio-app-performance/
            

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-selection-process-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3010
    type: HTTP
    requestPath: /interviews/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-app-selection-process
  annotations:
    cloud.google.com/backend-config: '{"default": "app-selection-process-config"}'
spec:
  type: NodePort
  selector:
    app: selection-process
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
      nodePort: 31030
---
