###################################
# INGRESS
###################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  labels:
    name: gateway-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /candidate
        backend:
          service:
            name: servicio-app-candidate
            port:
              number: 80
      - pathType: Prefix
        path: /projects
        backend:
          service:
            name: servicio-app-projects
            port:
              number: 80
      - pathType: Prefix
        path: /company
        backend:
          service:
            name: servicio-app-company
            port:
              number: 80
#      - pathType: Prefix
#        path: /app_performance
#        backend:
#          service:
#            name: servicio-app_performance
#            port:
#              number: 80
#      - pathType: Prefix
#        path: /app_selection_process
#        backend:
#          service:
#            name: servicio-publicnew
#            port:
#              number: 80
