###################################
# app_candidate
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance
  labels:
    app: performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: performance
  template:
    metadata:
      labels:
        app: performance
    spec:
      containers:
        - name: performance
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/abc-jobs-dockers/performance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3006
          env:
            - name: "SQLALCHEMY_DATABASE_URI"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: uri
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: DATABASE_URL

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-performance-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3006
    type: HTTP
    requestPath: /performance/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-app-performance
  annotations:
    cloud.google.com/backend-config: '{"default": "app-performance-config"}'
spec:
  type: NodePort
  selector:
    app: performance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
      nodePort: 31026
---
