name: test sonarcloud
run-name: ${{ github.actor }} is test codecov App Web 🚀
on:
  push:

jobs:
  codecov:
    name: upload coverage codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: postgres test
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          database: candidate_db

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalación de app_candidate
        run: |
          python -m pip install --upgrade pip
          pip install -r app_candidate/requirements.txt

      - name: Correr pruebas app_candidate
        id: correr-pruebas-usuarios
        run: |
          pytest --cov=app_candidate app_candidate/test_candidate_app.py --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}